let str = "Привет";
str;
str.length;
str[0];
str[str.length-1];
str.slice(1,3);
str.toLowerCase();
str.toUpperCase();
let text = "  СтРоКа  ";
let str1 = text.toLowerCase().trim();
str1[0].toUpperCase()+str1.slice(1);